kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-container
  labels:
    type: ssd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      type: ssd
