apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-ingress-role
  namespace: ingress
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
