apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-ingress-rolebinding
  namespace: ingress
subjects:
- kind: ServiceAccount
  name: sa-ingress
  namespace: ingress
roleRef:
  kind: Role
  name: sa-ingress-role
  apiGroup: rbac.authorization.k8s.io
