apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysqllabel
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: "MYSQL_USER"
          value: "mysql"
        - name: "MYSQL_PASSWORD"
          value: "mysql"
        - name: "MYSQL_DATABASE"
          value: "sample"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "supersecret"
      ports:
      - containerPort: 3306
