apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
spec:
  type: NodePort
  selector:
    app: nginx-label
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
      targetPort: 80
      #loadBalancerIP: 3.135.119.31
