apiVersion: v1
kind: Pod
metadata:
  name: path2
  labels:
    app: path2
  namespace: ingress
spec:
  containers:
    - name: path2
      image: customimage
      ports:
      - containerPort: 80
      imagePullPolicy: IfNotPresent
