apiVersion: v1
kind: Pod
metadata:
  name: path1
  labels:
    app: path1
  namespace: ingress
spec:
  containers:
    - name: path1
      image: customimage
      ports:
      - containerPort: 80
      imagePullPolicy: IfNotPresent
