apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: krishna
spec:
  usages:
  - digital signature
  - key encipherment
  - server auth
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1Z6Q0NBVDhDQVFBd0VqRVFNQTRHQTFVRUF3d0hhM0pwYzJodVlUQ0NBU0l3RFFZSktvWklodmNOQVFFQgpCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOeENPRk9obGRDK2krRkp5ZTBTQ1B1ZVRta01WK0Z6cjhRSlJXWCtTalloCjV2MlhYOFMwVDhKWHEyZUQrMjFJT2pNaVd2YlVuam5GK3N4MEg3WlBLaHZpcTl2RDJJQTNHVUl2a1VEWTZudFkKdGNEWlRjQ25IUXZHVjYxa1U5R3lhT1FZTE1ReVVWcDdJTnBNUjFrTjZlV2V5M1d6QVZuT3JaQld5TTkvSEw5Tgp1T05hc1JZQ2pCZzU3VWY2VEMvRjVMbE55THFHOVUwSlFOUEFJOVhZVjNvZTJiTnVWalU5WTAvYUpDQWFydlZ4Cnp5WGdUVjhObGQzK3o3N0RPc2wrSC90NTA1UmRpQzBpZzFVelVYUzRDS2lpTzRTTlE5cnBqT3VYUFVWc0RqcUEKeG5Wemt3ZTRKNDJoR3VkK0JyZ3dtZDNOZnVxeGFObEd6NE9nYTJUWnhORUNBd0VBQWFBQU1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUFOOHNETVJ4S0wvRlFuSjJ1d3VvZFI4YklLa0JpRlB1aEN0dXpQQnJEdE83QS9CK2NzCjNuNzlqV1QzZ2REZlVBamNRTlFTa1doRm05ZENlTGtqUE1wWG9OVTl3aHdIaXRlcC9HM2dKR01LSFoyZ1hDM1AKZWV4QWFXRTlJMzcrc1BqbmZOUjJ4bHdEQS9FT0M5Q2l5TUszc0RNeEF1dHRhdHljaE1LOU1XeS9LSmZscXlRMApqOUpiQytRa2F3TkVkN29zNXpSVW5KQWhFT3diYjE1N3Nrd3pxcDdNOVJPRS9kbVVkM1o4TVdPQ3hlbHlBVnhyCitNWTRKNDJkSGdPWUdGcmxhRkJDd0kxRWI3N2h0dHhIa1RGUFNmSGpRSkJnNmIyMlZ1QUh6d3FJcUVocVpyYkUKYXZMS2o2ME9SUEdIUEM2OXFtb2srQmdzc1lLcWxnUm9QZlJhCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=

