apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://172.31.44.79:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: mohan
    namespace: ingress
  name: mohan@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: mohan
  user:
    client-certificate: /etc/kubernetes/pki/mohan.crt
    client-key: /etc/kubernetes/pki/mohan.key
