apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: krishna-rolebinding
subjects:
- kind: User
  name: krishna
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: krishan-role
  apiGroup: rbac.authorization.k8s.io
